{{- if .Values.eventing.install -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventing-controller
  namespace: knative-eventing

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bus-operator
  namespace: knative-eventing
{{- end -}}
