{{- if .Values.build.install -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: istio-installation-job
  namespace: kube-system
  annotations:
      "helm.sh/hook": "pre-install"
      "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      name: istio-installation-job
    spec:
      serviceAccountName: tiller
      containers:
        - name: helm
          image: dtzar/helm-kubectl # dtzar/helm-kubectl #linkyard/docker-helm #
          command: ["/bin/sh","-c"]
          args: [ "wget -qO- https://github.com/istio/istio/archive/{{ .Values.istio.version }}.tar.gz | tar xvz;helm upgrade istio -i istio-{{ .Values.istio.version }}/install/kubernetes/helm/istio --set global.tag={{ .Values.istio.version }} --namespace istio-system" ] #args: ["helm ls"]
        - name:  kubectl
          image: dtzar/helm-kubectl
          command: ["/bin/sh","-c"]  #command: ["kubectl"]
          args: ["kubectl label ns default --overwrite istio-injection=enabled"]
      restartPolicy: OnFailure
---
  
{{- end -}}


{{- if and .Values.istio.install -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: istio-deletion-job
  namespace: kube-system
  annotations:
      "helm.sh/hook": pre-delete
      "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: istio-deletion-job
    spec:
      serviceAccountName: tiller
      containers:
        - name: helm
          image: dtzar/helm-kubectl # dtzar/helm-kubectl #linkyard/docker-helm #
          command: ["/bin/sh","-c"]
          args: [ "helm del --purge istio" ] #args: ["helm ls"]
        - name:  kubectl
          image: dtzar/helm-kubectl
          command: ["/bin/sh","-c"]  #command: ["kubectl"]
          args: ["kubectl label ns default --overwrite istio-injection-"]
      restartPolicy: OnFailure
{{- end -}}
